---
- name: "Check for nutanix-exporter binary"
  stat:
    path: "/usr/local/bin/nutanix-exporter"
  changed_when: false
  register: nutanix_binary

- when: not nutanix_binary.stat.exists
  block:
    - name: "Download nutanix-exporter..."
      get_url:
        url: '{{ nutanix_exporter_url }}'
        dest: /usr/local/bin/nutanix-exporter
        timeout: 120
        mode: 0755

- name: "Create config file"
  template:
    src: config.yml
    dest: /etc/nutanix_exporter/
    mode: 0644
  notify: "restart nutanix_exporter"

- name: "Create symtemd for nutanix_exporter"
  template:
    src: nutanix_exporter.service.j2
    dest: /etc/systemd/system/nutanix_exporter.service
    mode: 0644
  notify: "restart nutanix_exporter"


- name: "Start nutanix_exporter.service"
  systemd:
    name: nutanix_exporter
    state: started
    enabled: true
    daemon_reload: true
